#!/bin/bash
declare -a cydia
cydia=($CYDIA)
if [ -e /System/Library/PrivateFrameworks/PhotosUI.framework ]; then
	mv -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/LunarCalendar7 /System/Library/WeeAppPlugins/LunarCalendar.bundle/LunarCalendar
	mv -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/Info7.plist /System/Library/WeeAppPlugins/LunarCalendar.bundle/Info.plist
	rm -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/WeeAppBackground.png
	rm -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/WeeAppBackground@2x.png
else
	rm -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/LunarCalendar7
	rm -f /System/Library/WeeAppPlugins/LunarCalendar.bundle/Info7.plist
	rm -f /System/Library/WeeAppPlugins/LunarCalendarAll.bundle/*
	rm -fr /System/Library/WeeAppPlugins/LunarCalendarAll.bundle
fi
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:restart' >&${cydia[0]}"
fi
exit 0
