#!/bin/bash
declare -a cydia
cydia=($CYDIA)
lcBundle="/System/Library/WeeAppPlugins/LunarCalendar.bundle"
lcAllBundle="/System/Library/WeeAppPlugins/LunarCalendarAll.bundle"
if [ -e /System/Library/PrivateFrameworks/AssertionServices.framework ]; then
	mv -f $lcBundle/LunarCalendarToday $lcBundle/LunarCalendar
	mv -f $lcBundle/Info-Today.plist $lcBundle/Info.plist
	rm -f $lcBundle/WeeAppBackground.png $lcBundle/WeeAppBackground@2x.png $lcBundle/pledit
	rm -fr $lcAllBundle
	if [[ ! -d /Library/WeeLoader/Plugins ]]; then
		mkdir -p /Library/WeeLoader/Plugins
	fi
	mv -f $lcBundle /Library/WeeLoader/Plugins/LunarCalendar.bundle
elif [ -e /System/Library/PrivateFrameworks/PhotosUI.framework ]; then
	mv -f $lcBundle/LunarCalendarToday $lcBundle/LunarCalendar
	mv -f $lcBundle/Info-Today.plist $lcBundle/Info.plist
	if [ -f $lcBundle/pledit ]; then
		sectionInfo="/var/mobile/Library/BulletinBoard/SectionInfo.plist"
		if [ -f $sectionInfo ]; then
			$lcBundle/pledit -rmkey "com.autopear.lunarcalendar" $sectionInfo 2>&1 1>/dev/null
			$lcBundle/pledit -rmkey "com.autopear.lunarcalendar.all" $sectionInfo 2>&1 1>/dev/null
			$lcBundle/pledit -convert binary1 $sectionInfo 2>&1 1>/dev/null
		fi
	fi
	rm -f $lcBundle/WeeAppBackground.png $lcBundle/WeeAppBackground@2x.png $lcBundle/pledit
	echo "Enable the widget in Settings > Notification Center > Today or Include."
else
	rm -f $lcBundle/LunarCalendarToday
	rm -f $lcBundle/Info-Today.plist
	rm -fr $lcAllBundle
fi
if [[ ${CYDIA+@} ]]; then
	eval "echo 'finish:restart' >&${cydia[0]}"
fi
exit 0
